AWSTemplateFormatVersion: "2010-09-09"

Resources:
  FakeResource:
    Type: AWS::CloudFormation::WaitConditionHandle

Outputs:
  FakeOutput:
    Description: "A fake output"
    Value: "This is a fake deploy"
