name: Deploy CloudFormation Stack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: awscredentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oidc-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify AWS Credentials in use
        run: |
          echo "Verificando identidade do usuário AWS..."
          aws sts get-caller-identity

      - name: Deploy VPC Stack
        id: vpc
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: caf-sftp-vpc
          template: ./cloudformation-web-app/deploy.template.yaml
          capabilities: CAPABILITY_IAM
          no-fail-on-empty-changeset: "1"
          tags: |
            Project=caf-sftp
            Environment=development
