name: Test CloudFormation Stack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      DOMAIN_URL: "sftp.combateafraude.com"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        id: awscredentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oidc-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ vars.AWS_REGION }}

      - name: Verify AWS Credentials in use
        run: |
          echo "Verificando identidade do usuário AWS..."
          aws sts get-caller-identity

      - name: Deploy Test Stack
        id: test
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: caf-sftp-vpc
          template: ./deployment/test.template.yaml
          capabilities: CAPABILITY_IAM
          no-fail-on-empty-changeset: true
          tags: |
            Project=caf-sftp 
            Environment=development

      - name: FakeOutput Test
        run: |
          echo "${{ steps.test.outputs.FakeOutput }}"
          echo "${{ steps.awscredentials.outputs.aws-account-id }}"
          echo "$DOMAIN_URL"
